// src/components/SignIn/SignIn.vue
<template>
      <div class="sign-in-container">
      <div class="sign-in-wrapper">
        <h1 class="sign-in-title">Sign In</h1>
          <GoogleButton></GoogleButton>
        <router-link to='/game' class="skip">Skip</router-link>
      </div>
    </div>
</template>

<script>
import GoogleButton from './GoogleButton/GoogleButton.vue';

export default {
  name: 'SignIn',
  components: {
    GoogleButton
  },
}
</script>

<style lang="scss" src='./SignIn.scss'></style>

// src/components/SignIn/SignIn.jsx
import React, { Component } from "react";
import { Link } from "react-router-dom";
import './SignIn.scss';

export default class SignIn extends Component {
  render() {
    return(
      <div className="sign-in-container">
        <div className="sign-in-wrapper">
          <h1 className="sign-in-title">Sign In</h1>
          <button className="sign-in-button"><img src="https://i.ibb.co/NxYZR5b/google-icon.png" alt="google-icon" /> Sign In With Google</button>
          <Link to='/game' className="skip" >Skip</Link>
        </div>
      </div>
    );
  }
}
